service: web

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-domain-manager # Load the community plugin for custom domains installed with npm
  - ./scripts # Load our custom scripts plugin

build:
  esbuild: true

package:
  patterns:
    - "!app/**"
    - app/build/**

custom:
  customDomain:
    domainName: ${param:customDomainName}
    certificateArn: ${param:customDomainCertificateARN}
    stage: ""
    endpointType: "regional"
    apiType: http
    autoDomain: true
    enabled: ${param:customDomainNameEnabled}

  # This property is expected by our custom scripts plugin.
  scripts:
    hooks:
      # This hook builds the React App. It sets the environment variables for
      # the Chat and Auth APIs and then runs the build script.
      "before:esbuild-package:package": cd website/app && VITE_CHAT_API_URL='${param:chatApiUrl}' VITE_AUTH_API_URL='${param:authApiUrl}' npm run build

functions:
  app:
    handler: index.handler
    events:
      - httpApi: "*"
