name: Deploy PR Preview

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  remove:
    name: deploy-pr-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Configure AWS Credentials - Serverless Marketing AWS Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::488110005556:role/GithubActionsDeploymentRole
          aws-region: us-east-1
      - name: Serverless Deploy - PR Preview
        uses: serverless/github-action@v4
        with:
          args: deploy --stage pr-${{ github.event.pull_request.number }}
        env:
          SERVERLESS_LICENSE_KEY: ${{ secrets.SERVERLESS_LICENSE_KEY }}
